# Generated by Django 5.0.1 on 2024-03-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('projects', models.JSONField(blank=True, null=True)),
                ('professions', models.JSONField(blank=True, null=True)),
                ('hear_about_us', models.CharField(max_length=40)),
            ],
        ),
    ]
